// Decked Out - Official Complete Database
// Synchronized: 62 Series 1 Cards with UI, Animated Spritesheets

const GAME_CARDS = [
  {
    "id": "s1-046",
    "series": 1,
    "number": 46,
    "code": "#1-046",
    "name": "Alley Cutlass",
    "class": "Swordsman",
    "rarity": "Uncommon",
    "cost": 1,
    "damage": 6,
    "damageType": "Physical",
    "isSplash": false,
    "armor": 0,
    "ward": 0,
    "healing": 0,
    "manaGain": 0,
    "buffAmount": 0,
    "buffDuration": 0,
    "debuffAmount": 0,
    "debuffDuration": 0,
    "burn": 0,
    "bleed": 0,
    "poison": 0,
    "stunChance": 0,
    "speedBonus": 0,
    "scrapGain": 0,
    "scrapCost": 0,
    "spendAllScrap": false,
    "cardsToDraw": 0,
    "cardsToDiscard": 0,
    "cardsToRetrieve": 0,
    "description": "",
    "image": "assets/cards/Alley Cutlass.png",
    "staticImage": "assets/cards/Alley Cutlass.png",
    "animImage": null,
    "isAnimated": false
  },
  {
    "id": "s1-032",
    "series": 1,
    "number": 32,
    "code": "#1-032",
    "name": "Anvil",
    "class": "Swordsman",
    "rarity": "Uncommon",
    "cost": 2,
    "damage": 6,
    "damageType": "Physical",
    "isSplash": false,
    "armor": 6,
    "ward": 0,
    "healing": 0,
    "manaGain": 0,
    "buffAmount": 0,
    "buffDuration": 0,
    "debuffAmount": 0,
    "debuffDuration": 0,
    "burn": 0,
    "bleed": 0,
    "poison": 0,
    "stunChance": 0,
    "speedBonus": 0,
    "scrapGain": 0,
    "scrapCost": 0,
    "spendAllScrap": false,
    "cardsToDraw": 0,
    "cardsToDiscard": 0,
    "cardsToRetrieve": 0,
    "description": "A heavy weapon that hits solidly and leaves you braced behind steel.",
    "image": "assets/cards/Anvil.png",
    "staticImage": "assets/cards/Anvil.png",
    "animImage": null,
    "isAnimated": false
  },
  {
    "id": "s1-013",
    "series": 1,
    "number": 13,
    "code": "#1-013",
    "name": "Arrow",
    "class": "Swordsman",
    "rarity": "Rare",
    "cost": 2,
    "damage": 8,
    "damageType": "Physical",
    "isSplash": false,
    "armor": 0,
    "ward": 0,
    "healing": 0,
    "manaGain": 0,
    "buffAmount": 0,
    "buffDuration": 0,
    "debuffAmount": 0,
    "debuffDuration": 0,
    "burn": 0,
    "bleed": 4,
    "poison": 0,
    "stunChance": 0,
    "speedBonus": 0,
    "scrapGain": 0,
    "scrapCost": 0,
    "spendAllScrap": false,
    "cardsToDraw": 0,
    "cardsToDiscard": 0,
    "cardsToRetrieve": 0,
    "description": "A lighter arrow that chips away at enemies.",
    "image": "assets/cards/Arrow.png",
    "staticImage": "assets/cards/Arrow.png",
    "animImage": null,
    "isAnimated": false
  },
  {
    "id": "s1-042",
    "series": 1,
    "number": 42,
    "code": "#1-042",
    "name": "Ashmaw Colossus",
    "class": "Monster",
    "rarity": "Epic",
    "cost": 4,
    "damage": 14,
    "damageType": "Magic",
    "isSplash": true,
    "armor": 0,
    "ward": 0,
    "healing": 0,
    "manaGain": 0,
    "buffAmount": 0,
    "buffDuration": 0,
    "debuffAmount": 0,
    "debuffDuration": 0,
    "burn": 4,
    "bleed": 0,
    "poison": 0,
    "stunChance": 0,
    "speedBonus": 0,
    "scrapGain": 0,
    "scrapCost": 0,
    "spendAllScrap": false,
    "cardsToDraw": 0,
    "cardsToDiscard": 0,
    "cardsToRetrieve": 0,
    "description": "",
    "image": "assets/cards/Ashmaw Colossus.png",
    "staticImage": "assets/cards/Ashmaw Colossus.png",
    "animImage": null,
    "isAnimated": false
  },
  {
    "id": "s1-062",
    "series": 1,
    "number": 62,
    "code": "#1-062",
    "name": "Back-Alley Salvager",
    "class": "Goblins",
    "rarity": "Uncommon",
    "cost": 2,
    "damage": 0,
    "damageType": "None",
    "isSplash": false,
    "armor": 0,
    "ward": 0,
    "healing": 0,
    "manaGain": 0,
    "buffAmount": 0,
    "buffDuration": 0,
    "debuffAmount": 0,
    "debuffDuration": 0,
    "burn": 0,
    "bleed": 0,
    "poison": 0,
    "stunChance": 0,
    "speedBonus": 0,
    "scrapGain": 0,
    "scrapCost": 0,
    "spendAllScrap": false,
    "cardsToDraw": 0,
    "cardsToDiscard": 0,
    "cardsToRetrieve": 1,
    "description": "A scavenger who pulls one card back out of the trash pile.",
    "image": "assets/cards/anim/BackalleySalvagerG.webp",
    "staticImage": "assets/cards/BackalleySalvagerG.png",
    "animImage": "assets/cards/anim/BackalleySalvagerG.webp",
    "isAnimated": true
  },
  {
    "id": "s1-009",
    "series": 1,
    "number": 9,
    "code": "#1-009",
    "name": "Backstabbing Boomerang",
    "class": "Swordsman",
    "rarity": "Rare",
    "cost": 2,
    "damage": 6,
    "damageType": "Magic",
    "isSplash": true,
    "armor": 0,
    "ward": 0,
    "healing": 0,
    "manaGain": 0,
    "buffAmount": 0,
    "buffDuration": 0,
    "debuffAmount": 0,
    "debuffDuration": 0,
    "burn": 0,
    "bleed": 0,
    "poison": 0,
    "stunChance": 0,
    "speedBonus": 0,
    "scrapGain": 0,
    "scrapCost": 0,
    "spendAllScrap": false,
    "cardsToDraw": 0,
    "cardsToDiscard": 0,
    "cardsToRetrieve": 0,
    "description": "Deal 18 magic damage. Reduce enemy armor by 5.",
    "image": "assets/cards/BackstabbingBoomerang.png",
    "staticImage": "assets/cards/BackstabbingBoomerang.png",
    "animImage": null,
    "isAnimated": false
  },
  {
    "id": "s1-047",
    "series": 1,
    "number": 47,
    "code": "#1-047",
    "name": "Bastion Lancer",
    "class": "Swordsman",
    "rarity": "Rare",
    "cost": 2,
    "damage": 6,
    "damageType": "Physical",
    "isSplash": false,
    "armor": 7,
    "ward": 0,
    "healing": 0,
    "manaGain": 0,
    "buffAmount": 0,
    "buffDuration": 0,
    "debuffAmount": 0,
    "debuffDuration": 0,
    "burn": 0,
    "bleed": 3,
    "poison": 0,
    "stunChance": 0,
    "speedBonus": 0,
    "scrapGain": 0,
    "scrapCost": 0,
    "spendAllScrap": false,
    "cardsToDraw": 0,
    "cardsToDiscard": 0,
    "cardsToRetrieve": 0,
    "description": "",
    "image": "assets/cards/Bastion Lancer.png",
    "staticImage": "assets/cards/Bastion Lancer.png",
    "animImage": null,
    "isAnimated": false
  },
  {
    "id": "s1-033",
    "series": 1,
    "number": 33,
    "code": "#1-033",
    "name": "Blink",
    "class": "Wild Mages",
    "rarity": "Exotic",
    "cost": 4,
    "damage": 0,
    "damageType": "Physical",
    "isSplash": false,
    "armor": 0,
    "ward": 0,
    "healing": 0,
    "manaGain": 0,
    "buffAmount": 0,
    "buffDuration": 0,
    "debuffAmount": 0,
    "debuffDuration": 0,
    "burn": 0,
    "bleed": 0,
    "poison": 0,
    "stunChance": 0,
    "speedBonus": 0,
    "scrapGain": 0,
    "scrapCost": 0,
    "spendAllScrap": false,
    "cardsToDraw": 0,
    "cardsToDiscard": 0,
    "cardsToRetrieve": 0,
    "description": "A high-stakes gamble with a 35% chance to end combat instantly (non-boss). Failure costs 5 max health.",
    "image": "assets/cards/anim/Blink.webp",
    "staticImage": "assets/cards/Blink.png",
    "animImage": "assets/cards/anim/Blink.webp",
    "isAnimated": true
  },
  {
    "id": "s1-053",
    "series": 1,
    "number": 53,
    "code": "#1-053",
    "name": "Bloodmoon Hexer",
    "class": "Wild Mages",
    "rarity": "Rare",
    "cost": 2,
    "damage": 8,
    "damageType": "Magic",
    "isSplash": false,
    "armor": 0,
    "ward": 0,
    "healing": 0,
    "manaGain": 0,
    "buffAmount": 0,
    "buffDuration": 0,
    "debuffAmount": 0,
    "debuffDuration": 0,
    "burn": 0,
    "bleed": 0,
    "poison": 0,
    "stunChance": 0,
    "speedBonus": 0,
    "scrapGain": 0,
    "scrapCost": 0,
    "spendAllScrap": false,
    "cardsToDraw": 0,
    "cardsToDiscard": 0,
    "cardsToRetrieve": 0,
    "description": "",
    "image": "assets/cards/Bloodmoon Hexer.png",
    "staticImage": "assets/cards/Bloodmoon Hexer.png",
    "animImage": null,
    "isAnimated": false
  },
  {
    "id": "s1-041",
    "series": 1,
    "number": 41,
    "code": "#1-041",
    "name": "Bone Pit Abomination",
    "class": "Monster",
    "rarity": "Epic",
    "cost": 3,
    "damage": 9,
    "damageType": "Physical",
    "isSplash": false,
    "armor": 0,
    "ward": 0,
    "healing": 0,
    "manaGain": 1,
    "buffAmount": 0,
    "buffDuration": 0,
    "debuffAmount": 0,
    "debuffDuration": 0,
    "burn": 0,
    "bleed": 0,
    "poison": 0,
    "stunChance": 0,
    "speedBonus": 0,
    "scrapGain": 0,
    "scrapCost": 0,
    "spendAllScrap": false,
    "cardsToDraw": 0,
    "cardsToDiscard": 0,
    "cardsToRetrieve": 0,
    "description": "",
    "image": "assets/cards/Bonepit abomination .png",
    "staticImage": "assets/cards/Bonepit abomination .png",
    "animImage": null,
    "isAnimated": false
  },
  {
    "id": "s1-001",
    "series": 1,
    "number": 1,
    "code": "#1-001",
    "name": "Cat",
    "class": "Animal",
    "rarity": "Common",
    "cost": 1,
    "damage": 0,
    "damageType": "None",
    "isSplash": false,
    "armor": 0,
    "ward": 0,
    "healing": 4,
    "manaGain": 1,
    "buffAmount": 0,
    "buffDuration": 2,
    "debuffAmount": 0,
    "debuffDuration": 0,
    "burn": 0,
    "bleed": 0,
    "poison": 0,
    "stunChance": 0,
    "speedBonus": 0,
    "scrapGain": 0,
    "scrapCost": 0,
    "spendAllScrap": false,
    "cardsToDraw": 0,
    "cardsToDiscard": 0,
    "cardsToRetrieve": 0,
    "description": "A friendly cat that heals you and gives you speed!",
    "image": "assets/cards/Cat.png",
    "staticImage": "assets/cards/Cat.png",
    "animImage": null,
    "isAnimated": false
  },
  {
    "id": "s1-055",
    "series": 1,
    "number": 55,
    "code": "#1-055",
    "name": "Cinder Archivist",
    "class": "Wild Mages",
    "rarity": "Legendary",
    "cost": 4,
    "damage": 12,
    "damageType": "Magic",
    "isSplash": false,
    "armor": 0,
    "ward": 0,
    "healing": 0,
    "manaGain": 0,
    "buffAmount": 0,
    "buffDuration": 0,
    "debuffAmount": 0,
    "debuffDuration": 0,
    "burn": 6,
    "bleed": 0,
    "poison": 0,
    "stunChance": 0,
    "speedBonus": 0,
    "scrapGain": 0,
    "scrapCost": 0,
    "spendAllScrap": false,
    "cardsToDraw": 0,
    "cardsToDiscard": 0,
    "cardsToRetrieve": 0,
    "description": "",
    "image": "assets/cards/Cinder Archivist.png",
    "staticImage": "assets/cards/Cinder Archivist.png",
    "animImage": null,
    "isAnimated": false
  },
  {
    "id": "s1-038",
    "series": 1,
    "number": 38,
    "code": "#1-038",
    "name": "Cinder Fox",
    "class": "Animal",
    "rarity": "Common",
    "cost": 2,
    "damage": 6,
    "damageType": "Physical",
    "isSplash": false,
    "armor": 0,
    "ward": 0,
    "healing": 0,
    "manaGain": 0,
    "buffAmount": 0,
    "buffDuration": 0,
    "debuffAmount": 0,
    "debuffDuration": 0,
    "burn": 0,
    "bleed": 0,
    "poison": 0,
    "stunChance": 0,
    "speedBonus": 3,
    "scrapGain": 0,
    "scrapCost": 0,
    "spendAllScrap": false,
    "cardsToDraw": 0,
    "cardsToDiscard": 0,
    "cardsToRetrieve": 0,
    "description": "",
    "image": "assets/cards/CinderFoxBrowser.png",
    "staticImage": "assets/cards/CinderFoxBrowser.png",
    "animImage": null,
    "isAnimated": false
  },
  {
    "id": "s1-043",
    "series": 1,
    "number": 43,
    "code": "#1-043",
    "name": "Crypt Broodmother",
    "class": "Monster",
    "rarity": "Uncommon",
    "cost": 2,
    "damage": 6,
    "damageType": "Magic",
    "isSplash": false,
    "armor": 0,
    "ward": 0,
    "healing": 0,
    "manaGain": 0,
    "buffAmount": 0,
    "buffDuration": 0,
    "debuffAmount": 0,
    "debuffDuration": 0,
    "burn": 0,
    "bleed": 0,
    "poison": 0,
    "stunChance": 0,
    "speedBonus": 0,
    "scrapGain": 0,
    "scrapCost": 0,
    "spendAllScrap": false,
    "cardsToDraw": 0,
    "cardsToDiscard": 0,
    "cardsToRetrieve": 1,
    "description": "",
    "image": "assets/cards/Crypt Broodmother.png",
    "staticImage": "assets/cards/Crypt Broodmother.png",
    "animImage": null,
    "isAnimated": false
  },
  {
    "id": "s1-019",
    "series": 1,
    "number": 19,
    "code": "#1-019",
    "name": "Daddy Demon Litionist",
    "class": "Monster",
    "rarity": "Legendary",
    "cost": 4,
    "damage": 22,
    "damageType": "Physical",
    "isSplash": true,
    "armor": 0,
    "ward": 0,
    "healing": 0,
    "manaGain": 0,
    "buffAmount": 0,
    "buffDuration": 0,
    "debuffAmount": 0,
    "debuffDuration": 0,
    "burn": 0,
    "bleed": 0,
    "poison": 0,
    "stunChance": 0,
    "speedBonus": 0,
    "scrapGain": 0,
    "scrapCost": 0,
    "spendAllScrap": false,
    "cardsToDraw": 0,
    "cardsToDiscard": 0,
    "cardsToRetrieve": 0,
    "description": "The dad of the lil demon Litionist!",
    "image": "assets/cards/Daddy Demon-litionist.png",
    "staticImage": "assets/cards/Daddy Demon-litionist.png",
    "animImage": null,
    "isAnimated": false
  },
  {
    "id": "s1-026",
    "series": 1,
    "number": 26,
    "code": "#1-026",
    "name": "Dice",
    "class": "Monster",
    "rarity": "Epic",
    "cost": 2,
    "damage": 5,
    "damageType": "Physical",
    "isSplash": false,
    "armor": 0,
    "ward": 0,
    "healing": 0,
    "manaGain": 0,
    "buffAmount": 0,
    "buffDuration": 0,
    "debuffAmount": 0,
    "debuffDuration": 0,
    "burn": 0,
    "bleed": 0,
    "poison": 0,
    "stunChance": 0,
    "speedBonus": 0,
    "scrapGain": 0,
    "scrapCost": 0,
    "spendAllScrap": false,
    "cardsToDraw": 0,
    "cardsToDiscard": 0,
    "cardsToRetrieve": 0,
    "description": "Rolls a wild strike between 2 and 20 damage.",
    "image": "assets/cards/Dice.png",
    "staticImage": "assets/cards/Dice.png",
    "animImage": null,
    "isAnimated": false
  },
  {
    "id": "s1-005",
    "series": 1,
    "number": 5,
    "code": "#1-005",
    "name": "Dog",
    "class": "Animal",
    "rarity": "Common",
    "cost": 1,
    "damage": 0,
    "damageType": "Physical",
    "isSplash": false,
    "armor": 4,
    "ward": 0,
    "healing": 3,
    "manaGain": 1,
    "buffAmount": 3,
    "buffDuration": 2,
    "debuffAmount": 3,
    "debuffDuration": 2,
    "burn": 0,
    "bleed": 0,
    "poison": 0,
    "stunChance": 0,
    "speedBonus": 0,
    "scrapGain": 0,
    "scrapCost": 0,
    "spendAllScrap": false,
    "cardsToDraw": 0,
    "cardsToDiscard": 0,
    "cardsToRetrieve": 0,
    "description": "A loyal dog that attacks, heals, buffs you, debuffs enemies, and gives speed!",
    "image": "assets/cards/dog.png",
    "staticImage": "assets/cards/dog.png",
    "animImage": null,
    "isAnimated": false
  },
  {
    "id": "s1-045",
    "series": 1,
    "number": 45,
    "code": "#1-045",
    "name": "Ember Tyrant",
    "class": "Monster",
    "rarity": "Legendary",
    "cost": 4,
    "damage": 16,
    "damageType": "Physical",
    "isSplash": false,
    "armor": 0,
    "ward": 0,
    "healing": 0,
    "manaGain": 0,
    "buffAmount": 0,
    "buffDuration": 0,
    "debuffAmount": 0,
    "debuffDuration": 0,
    "burn": 6,
    "bleed": 0,
    "poison": 0,
    "stunChance": 0,
    "speedBonus": 0,
    "scrapGain": 0,
    "scrapCost": 0,
    "spendAllScrap": false,
    "cardsToDraw": 0,
    "cardsToDiscard": 0,
    "cardsToRetrieve": 0,
    "description": "",
    "image": "assets/cards/Ember Tyrant.png",
    "staticImage": "assets/cards/Ember Tyrant.png",
    "animImage": null,
    "isAnimated": false
  },
  {
    "id": "s1-049",
    "series": 1,
    "number": 49,
    "code": "#1-049",
    "name": "Execution Cadet",
    "class": "Swordsman",
    "rarity": "Uncommon",
    "cost": 1,
    "damage": 5,
    "damageType": "Physical",
    "isSplash": false,
    "armor": 0,
    "ward": 0,
    "healing": 0,
    "manaGain": 0,
    "buffAmount": 0,
    "buffDuration": 0,
    "debuffAmount": 0,
    "debuffDuration": 0,
    "burn": 0,
    "bleed": 0,
    "poison": 0,
    "stunChance": 0,
    "speedBonus": 0,
    "scrapGain": 0,
    "scrapCost": 0,
    "spendAllScrap": false,
    "cardsToDraw": 0,
    "cardsToDiscard": 0,
    "cardsToRetrieve": 0,
    "description": "",
    "image": "assets/cards/Executioner Cadet.png",
    "staticImage": "assets/cards/Executioner Cadet.png",
    "animImage": null,
    "isAnimated": false
  },
  {
    "id": "s1-035",
    "series": 1,
    "number": 35,
    "code": "#1-035",
    "name": "Fangs",
    "class": "Animal",
    "rarity": "Legendary",
    "cost": 3,
    "damage": 14,
    "damageType": "Physical",
    "isSplash": false,
    "armor": 0,
    "ward": 0,
    "healing": 0,
    "manaGain": 0,
    "buffAmount": 0,
    "buffDuration": 0,
    "debuffAmount": 0,
    "debuffDuration": 0,
    "burn": 0,
    "bleed": 8,
    "poison": 0,
    "stunChance": 0,
    "speedBonus": 6,
    "scrapGain": 0,
    "scrapCost": 0,
    "spendAllScrap": false,
    "cardsToDraw": 0,
    "cardsToDiscard": 0,
    "cardsToRetrieve": 0,
    "description": "A savage beast that tears in fast, then pays for it in blood.",
    "image": "assets/cards/Fangs.png",
    "staticImage": "assets/cards/Fangs.png",
    "animImage": null,
    "isAnimated": false
  },
  {
    "id": "s1-027",
    "series": 1,
    "number": 27,
    "code": "#1-027",
    "name": "Fenrir",
    "class": "Animal",
    "rarity": "Legendary",
    "cost": 4,
    "damage": 22,
    "damageType": "Physical",
    "isSplash": false,
    "armor": 0,
    "ward": 0,
    "healing": 0,
    "manaGain": 0,
    "buffAmount": 0,
    "buffDuration": 0,
    "debuffAmount": 0,
    "debuffDuration": 0,
    "burn": 0,
    "bleed": 8,
    "poison": 0,
    "stunChance": 0,
    "speedBonus": 0,
    "scrapGain": 0,
    "scrapCost": 0,
    "spendAllScrap": false,
    "cardsToDraw": 0,
    "cardsToDiscard": 0,
    "cardsToRetrieve": 0,
    "description": "A colossal beast that tears through enemies and bleeds for its power.",
    "image": "assets/cards/Fenrir.png",
    "staticImage": "assets/cards/Fenrir.png",
    "animImage": null,
    "isAnimated": false
  },
  {
    "id": "s1-036",
    "series": 1,
    "number": 36,
    "code": "#1-036",
    "name": "Flask",
    "class": "Elixir",
    "rarity": "Common",
    "cost": 1,
    "damage": 0,
    "damageType": "Physical",
    "isSplash": false,
    "armor": 0,
    "ward": 0,
    "healing": 4,
    "manaGain": 1,
    "buffAmount": 0,
    "buffDuration": 0,
    "debuffAmount": 0,
    "debuffDuration": 0,
    "burn": 0,
    "bleed": 0,
    "poison": 0,
    "stunChance": 0,
    "speedBonus": 2,
    "scrapGain": 0,
    "scrapCost": 0,
    "spendAllScrap": false,
    "cardsToDraw": 0,
    "cardsToDiscard": 0,
    "cardsToRetrieve": 0,
    "description": "A simple recovery flask that steadies you and keeps you going.",
    "image": "assets/cards/Flask.png",
    "staticImage": "assets/cards/Flask.png",
    "animImage": null,
    "isAnimated": false
  },
  {
    "id": "s1-024",
    "series": 1,
    "number": 24,
    "code": "#1-024",
    "name": "Ghost",
    "class": "Monster",
    "rarity": "Uncommon",
    "cost": 1,
    "damage": 5,
    "damageType": "Magic",
    "isSplash": false,
    "armor": 0,
    "ward": 0,
    "healing": 3,
    "manaGain": 0,
    "buffAmount": 0,
    "buffDuration": 0,
    "debuffAmount": 0,
    "debuffDuration": 0,
    "burn": 0,
    "bleed": 0,
    "poison": 0,
    "stunChance": 0,
    "speedBonus": 3,
    "scrapGain": 0,
    "scrapCost": 0,
    "spendAllScrap": false,
    "cardsToDraw": 0,
    "cardsToDiscard": 0,
    "cardsToRetrieve": 0,
    "description": "A restless spirit that slips through armor.",
    "image": "assets/cards/Ghost.png",
    "staticImage": "assets/cards/Ghost.png",
    "animImage": null,
    "isAnimated": false
  },
  {
    "id": "s1-044",
    "series": 1,
    "number": 44,
    "code": "#1-044",
    "name": "Gravechain Horror",
    "class": "Monster",
    "rarity": "Epic",
    "cost": 3,
    "damage": 10,
    "damageType": "Physical",
    "isSplash": false,
    "armor": 0,
    "ward": 0,
    "healing": 0,
    "manaGain": 0,
    "buffAmount": 0,
    "buffDuration": 0,
    "debuffAmount": 0,
    "debuffDuration": 0,
    "burn": 0,
    "bleed": 0,
    "poison": 0,
    "stunChance": 0,
    "speedBonus": 3,
    "scrapGain": 0,
    "scrapCost": 0,
    "spendAllScrap": false,
    "cardsToDraw": 0,
    "cardsToDiscard": 0,
    "cardsToRetrieve": 1,
    "description": "",
    "image": "assets/cards/GraveChainHorror.png",
    "staticImage": "assets/cards/GraveChainHorror.png",
    "animImage": null,
    "isAnimated": false
  },
  {
    "id": "s1-025",
    "series": 1,
    "number": 25,
    "code": "#1-025",
    "name": "Graveyard",
    "class": "Monster",
    "rarity": "Exotic",
    "cost": 4,
    "damage": 0,
    "damageType": "Physical",
    "isSplash": false,
    "armor": 0,
    "ward": 0,
    "healing": 0,
    "manaGain": 0,
    "buffAmount": 0,
    "buffDuration": 0,
    "debuffAmount": 0,
    "debuffDuration": 0,
    "burn": 0,
    "bleed": 0,
    "poison": 0,
    "stunChance": 0,
    "speedBonus": 0,
    "scrapGain": 0,
    "scrapCost": 0,
    "spendAllScrap": false,
    "cardsToDraw": 0,
    "cardsToDiscard": 0,
    "cardsToRetrieve": 0,
    "description": "Summon 2 Ghosts to hand. Then summon 2 more cards: 20% Grim Reaper, otherwise Ghost. Activates Graveyard Aura for this run.",
    "image": "assets/cards/anim/Graveyard.webp",
    "staticImage": "assets/cards/Graveyard.png",
    "animImage": "assets/cards/anim/Graveyard.webp",
    "isAnimated": true
  },
  {
    "id": "s1-008",
    "series": 1,
    "number": 8,
    "code": "#1-008",
    "name": "Grim Reaper",
    "class": "Monster",
    "rarity": "Rare",
    "cost": 3,
    "damage": 12,
    "damageType": "Magic",
    "isSplash": false,
    "armor": 0,
    "ward": 0,
    "healing": 0,
    "manaGain": 0,
    "buffAmount": 0,
    "buffDuration": 0,
    "debuffAmount": 0,
    "debuffDuration": 0,
    "burn": 0,
    "bleed": 0,
    "poison": 0,
    "stunChance": 0,
    "speedBonus": 0,
    "scrapGain": 0,
    "scrapCost": 0,
    "spendAllScrap": false,
    "cardsToDraw": 0,
    "cardsToDiscard": 0,
    "cardsToRetrieve": 2,
    "description": "Deal 20 magic damage. Retrieve 3 cards from your discard pile to your hand.",
    "image": "assets/cards/GrimReaper.png",
    "staticImage": "assets/cards/GrimReaper.png",
    "animImage": null,
    "isAnimated": false
  },
  {
    "id": "s1-021",
    "series": 1,
    "number": 21,
    "code": "#1-021",
    "name": "Hedgehog",
    "class": "Animal",
    "rarity": "Rare",
    "cost": 2,
    "damage": 5,
    "damageType": "Physical",
    "isSplash": true,
    "armor": 0,
    "ward": 0,
    "healing": 0,
    "manaGain": 0,
    "buffAmount": 2,
    "buffDuration": 2,
    "debuffAmount": 0,
    "debuffDuration": 0,
    "burn": 0,
    "bleed": 3,
    "poison": 0,
    "stunChance": 0,
    "speedBonus": 0,
    "scrapGain": 0,
    "scrapCost": 0,
    "spendAllScrap": false,
    "cardsToDraw": 0,
    "cardsToDiscard": 0,
    "cardsToRetrieve": 0,
    "description": "A small but powerful hedgehog",
    "image": "assets/cards/Hedgehog.png",
    "staticImage": "assets/cards/Hedgehog.png",
    "animImage": null,
    "isAnimated": false
  },
  {
    "id": "s1-031",
    "series": 1,
    "number": 31,
    "code": "#1-031",
    "name": "Howls",
    "class": "Animal",
    "rarity": "Rare",
    "cost": 2,
    "damage": 6,
    "damageType": "Physical",
    "isSplash": true,
    "armor": 0,
    "ward": 0,
    "healing": 0,
    "manaGain": 0,
    "buffAmount": 3,
    "buffDuration": 2,
    "debuffAmount": 0,
    "debuffDuration": 0,
    "burn": 0,
    "bleed": 2,
    "poison": 0,
    "stunChance": 0,
    "speedBonus": 0,
    "scrapGain": 0,
    "scrapCost": 0,
    "spendAllScrap": false,
    "cardsToDraw": 0,
    "cardsToDiscard": 0,
    "cardsToRetrieve": 0,
    "description": "A pack of cursed howls that wound every enemy at once.",
    "image": "assets/cards/Howl.png",
    "staticImage": "assets/cards/Howl.png",
    "animImage": null,
    "isAnimated": false
  },
  {
    "id": "s1-039",
    "series": 1,
    "number": 39,
    "code": "#1-039",
    "name": "Iron Oath Duellist",
    "class": "Swordsman",
    "rarity": "Legendary",
    "cost": 3,
    "damage": 18,
    "damageType": "Physical",
    "isSplash": false,
    "armor": 8,
    "ward": 0,
    "healing": 0,
    "manaGain": 0,
    "buffAmount": 4,
    "buffDuration": 3,
    "debuffAmount": 0,
    "debuffDuration": 0,
    "burn": 0,
    "bleed": 0,
    "poison": 0,
    "stunChance": 0,
    "speedBonus": 0,
    "scrapGain": 0,
    "scrapCost": 0,
    "spendAllScrap": false,
    "cardsToDraw": 0,
    "cardsToDiscard": 0,
    "cardsToRetrieve": 0,
    "description": "",
    "image": "assets/cards/Iron Oath Duelist.png",
    "staticImage": "assets/cards/Iron Oath Duelist.png",
    "animImage": null,
    "isAnimated": false
  },
  {
    "id": "s1-060",
    "series": 1,
    "number": 60,
    "code": "#1-060",
    "name": "Junkshield Bruiser",
    "class": "Goblins",
    "rarity": "Common",
    "cost": 2,
    "damage": 0,
    "damageType": "Physical",
    "isSplash": false,
    "armor": 8,
    "ward": 2,
    "healing": 0,
    "manaGain": 0,
    "buffAmount": 0,
    "buffDuration": 0,
    "debuffAmount": 0,
    "debuffDuration": 0,
    "burn": 0,
    "bleed": 0,
    "poison": 0,
    "stunChance": 0,
    "speedBonus": 0,
    "scrapGain": 0,
    "scrapCost": 0,
    "spendAllScrap": false,
    "cardsToDraw": 0,
    "cardsToDiscard": 0,
    "cardsToRetrieve": 0,
    "description": "A bulky goblin brawler who slaps together protection from scrap.",
    "image": "assets/cards/anim/JunkshieldBruiserG.webp",
    "staticImage": "assets/cards/JunkshieldBruiserG.png",
    "animImage": "assets/cards/anim/JunkshieldBruiserG.webp",
    "isAnimated": true
  },
  {
    "id": "s1-051",
    "series": 1,
    "number": 51,
    "code": "#1-051",
    "name": "Lantern Owl",
    "class": "Wild Mages",
    "rarity": "Epic",
    "cost": 3,
    "damage": 8,
    "damageType": "Physical",
    "isSplash": false,
    "armor": 0,
    "ward": 0,
    "healing": 0,
    "manaGain": 0,
    "buffAmount": 0,
    "buffDuration": 0,
    "debuffAmount": 0,
    "debuffDuration": 0,
    "burn": 0,
    "bleed": 0,
    "poison": 0,
    "stunChance": 0,
    "speedBonus": 0,
    "scrapGain": 0,
    "scrapCost": 0,
    "spendAllScrap": false,
    "cardsToDraw": 0,
    "cardsToDiscard": 0,
    "cardsToRetrieve": 0,
    "description": "",
    "image": "assets/cards/Lantern Owl.png",
    "staticImage": "assets/cards/Lantern Owl.png",
    "animImage": null,
    "isAnimated": false
  },
  {
    "id": "s1-002",
    "series": 1,
    "number": 2,
    "code": "#1-002",
    "name": "Lava Launcher",
    "class": "Monster",
    "rarity": "Uncommon",
    "cost": 3,
    "damage": 8,
    "damageType": "Magic",
    "isSplash": true,
    "armor": 0,
    "ward": 0,
    "healing": 0,
    "manaGain": 0,
    "buffAmount": 2,
    "buffDuration": 2,
    "debuffAmount": 0,
    "debuffDuration": 0,
    "burn": 3,
    "bleed": 0,
    "poison": 0,
    "stunChance": 0,
    "speedBonus": 0,
    "scrapGain": 0,
    "scrapCost": 0,
    "spendAllScrap": false,
    "cardsToDraw": 0,
    "cardsToDiscard": 0,
    "cardsToRetrieve": 0,
    "description": "Launch molten lava at all enemies! Burns and reduces armor.",
    "image": "assets/cards/LavaLauncher.png",
    "staticImage": "assets/cards/LavaLauncher.png",
    "animImage": null,
    "isAnimated": false
  },
  {
    "id": "s1-010",
    "series": 1,
    "number": 10,
    "code": "#1-010",
    "name": "Lil Demon Litionist",
    "class": "Monster",
    "rarity": "Common",
    "cost": 3,
    "damage": 3,
    "damageType": "Physical",
    "isSplash": true,
    "armor": 0,
    "ward": 0,
    "healing": 0,
    "manaGain": 0,
    "buffAmount": 0,
    "buffDuration": 0,
    "debuffAmount": 0,
    "debuffDuration": 0,
    "burn": 1,
    "bleed": 0,
    "poison": 0,
    "stunChance": 0,
    "speedBonus": 0,
    "scrapGain": 0,
    "scrapCost": 0,
    "spendAllScrap": false,
    "cardsToDraw": 0,
    "cardsToDiscard": 0,
    "cardsToRetrieve": 0,
    "description": "Deal 25 physical damage to all enemies.",
    "image": "assets/cards/Lil' Demon-litionist.png",
    "staticImage": "assets/cards/Lil' Demon-litionist.png",
    "animImage": null,
    "isAnimated": false
  },
  {
    "id": "s1-003",
    "series": 1,
    "number": 3,
    "code": "#1-003",
    "name": "Magic Milkshake",
    "class": "Elixir",
    "rarity": "Uncommon",
    "cost": 2,
    "damage": 0,
    "damageType": "None",
    "isSplash": false,
    "armor": 0,
    "ward": 4,
    "healing": 6,
    "manaGain": 1,
    "buffAmount": 0,
    "buffDuration": 0,
    "debuffAmount": 0,
    "debuffDuration": 0,
    "burn": 0,
    "bleed": 0,
    "poison": 0,
    "stunChance": 0,
    "speedBonus": 0,
    "scrapGain": 0,
    "scrapCost": 0,
    "spendAllScrap": false,
    "cardsToDraw": 0,
    "cardsToDiscard": 0,
    "cardsToRetrieve": 0,
    "description": "A delicious milkshake that restores health, mana, and magic defense!",
    "image": "assets/cards/MagicMilkshake.png",
    "staticImage": "assets/cards/MagicMilkshake.png",
    "animImage": null,
    "isAnimated": false
  },
  {
    "id": "s1-011",
    "series": 1,
    "number": 11,
    "code": "#1-011",
    "name": "Mana Moon",
    "class": "Wild Mages",
    "rarity": "Legendary",
    "cost": 2,
    "damage": 0,
    "damageType": "None",
    "isSplash": false,
    "armor": 0,
    "ward": 8,
    "healing": 12,
    "manaGain": 4,
    "buffAmount": 0,
    "buffDuration": 0,
    "debuffAmount": 0,
    "debuffDuration": 0,
    "burn": 0,
    "bleed": 0,
    "poison": 0,
    "stunChance": 0,
    "speedBonus": 0,
    "scrapGain": 0,
    "scrapCost": 0,
    "spendAllScrap": false,
    "cardsToDraw": 0,
    "cardsToDiscard": 0,
    "cardsToRetrieve": 0,
    "description": "Restore 8 mana and heal for 30 HP. Free to play!",
    "image": "assets/cards/ManaMoon.png",
    "staticImage": "assets/cards/ManaMoon.png",
    "animImage": null,
    "isAnimated": false
  },
  {
    "id": "s1-017",
    "series": 1,
    "number": 17,
    "code": "#1-017",
    "name": "Mega Donut",
    "class": "Elixir",
    "rarity": "Exotic",
    "cost": 3,
    "damage": 0,
    "damageType": "None",
    "isSplash": false,
    "armor": 12,
    "ward": 12,
    "healing": 30,
    "manaGain": 0,
    "buffAmount": 0,
    "buffDuration": 0,
    "debuffAmount": 0,
    "debuffDuration": 0,
    "burn": 0,
    "bleed": 0,
    "poison": 0,
    "stunChance": 0,
    "speedBonus": 0,
    "scrapGain": 0,
    "scrapCost": 0,
    "spendAllScrap": false,
    "cardsToDraw": 0,
    "cardsToDiscard": 0,
    "cardsToRetrieve": 0,
    "description": "Eat the MegaDonut and instantly restore to full health.",
    "image": "assets/cards/anim/MegaDonut.webp",
    "staticImage": "assets/cards/MegaDonut.png",
    "animImage": "assets/cards/anim/MegaDonut.webp",
    "isAnimated": true
  },
  {
    "id": "s1-054",
    "series": 1,
    "number": 54,
    "code": "#1-054",
    "name": "Mirror Sigilist",
    "class": "Wild Mages",
    "rarity": "Rare",
    "cost": 2,
    "damage": 6,
    "damageType": "Magic",
    "isSplash": false,
    "armor": 0,
    "ward": 0,
    "healing": 0,
    "manaGain": 0,
    "buffAmount": 0,
    "buffDuration": 0,
    "debuffAmount": 0,
    "debuffDuration": 0,
    "burn": 0,
    "bleed": 0,
    "poison": 0,
    "stunChance": 0,
    "speedBonus": 0,
    "scrapGain": 0,
    "scrapCost": 0,
    "spendAllScrap": false,
    "cardsToDraw": 0,
    "cardsToDiscard": 0,
    "cardsToRetrieve": 0,
    "description": "",
    "image": "assets/cards/MirrorSigilist.png",
    "staticImage": "assets/cards/MirrorSigilist.png",
    "animImage": null,
    "isAnimated": false
  },
  {
    "id": "s1-030",
    "series": 1,
    "number": 30,
    "code": "#1-030",
    "name": "Moonbrew",
    "class": "Elixir",
    "rarity": "Rare",
    "cost": 2,
    "damage": 0,
    "damageType": "Physical",
    "isSplash": false,
    "armor": 0,
    "ward": 5,
    "healing": 8,
    "manaGain": 2,
    "buffAmount": 0,
    "buffDuration": 0,
    "debuffAmount": 0,
    "debuffDuration": 0,
    "burn": 0,
    "bleed": 0,
    "poison": 0,
    "stunChance": 0,
    "speedBonus": 0,
    "scrapGain": 0,
    "scrapCost": 0,
    "spendAllScrap": false,
    "cardsToDraw": 0,
    "cardsToDiscard": 0,
    "cardsToRetrieve": 0,
    "description": "A calming elixir that restores your body and refills your reserves.",
    "image": "assets/cards/MoonBrew.png",
    "staticImage": "assets/cards/MoonBrew.png",
    "animImage": null,
    "isAnimated": false
  },
  {
    "id": "s1-050",
    "series": 1,
    "number": 50,
    "code": "#1-050",
    "name": "Mossback Boar",
    "class": "Animal",
    "rarity": "Common",
    "cost": 2,
    "damage": 6,
    "damageType": "Physical",
    "isSplash": false,
    "armor": 0,
    "ward": 3,
    "healing": 3,
    "manaGain": 0,
    "buffAmount": 0,
    "buffDuration": 0,
    "debuffAmount": 0,
    "debuffDuration": 0,
    "burn": 0,
    "bleed": 0,
    "poison": 0,
    "stunChance": 0,
    "speedBonus": 0,
    "scrapGain": 0,
    "scrapCost": 0,
    "spendAllScrap": false,
    "cardsToDraw": 0,
    "cardsToDiscard": 0,
    "cardsToRetrieve": 0,
    "description": "",
    "image": "assets/cards/Mossback boar (Mr.png",
    "staticImage": "assets/cards/Mossback boar (Mr.png",
    "animImage": null,
    "isAnimated": false
  },
  {
    "id": "s1-015",
    "series": 1,
    "number": 15,
    "code": "#1-015",
    "name": "Mouse",
    "class": "Animal",
    "rarity": "Common",
    "cost": 1,
    "damage": 2,
    "damageType": "Physical",
    "isSplash": false,
    "armor": 0,
    "ward": 0,
    "healing": 2,
    "manaGain": 0,
    "buffAmount": 0,
    "buffDuration": 0,
    "debuffAmount": 0,
    "debuffDuration": 0,
    "burn": 0,
    "bleed": 0,
    "poison": 0,
    "stunChance": 0,
    "speedBonus": 2,
    "scrapGain": 0,
    "scrapCost": 0,
    "spendAllScrap": false,
    "cardsToDraw": 1,
    "cardsToDiscard": 0,
    "cardsToRetrieve": 0,
    "description": "Deal 2 physical damage. Draw 1 card. Gain 14 speed (dodge chance). Heal 4 HP.",
    "image": "assets/cards/Mouse.png",
    "staticImage": "assets/cards/Mouse.png",
    "animImage": null,
    "isAnimated": false
  },
  {
    "id": "s1-004",
    "series": 1,
    "number": 4,
    "code": "#1-004",
    "name": "Mystic Tea",
    "class": "Elixir",
    "rarity": "Rare",
    "cost": 2,
    "damage": 0,
    "damageType": "None",
    "isSplash": false,
    "armor": 0,
    "ward": 5,
    "healing": 7,
    "manaGain": 2,
    "buffAmount": 5,
    "buffDuration": 2,
    "debuffAmount": 0,
    "debuffDuration": 0,
    "burn": 0,
    "bleed": 0,
    "poison": 0,
    "stunChance": 0,
    "speedBonus": 0,
    "scrapGain": 0,
    "scrapCost": 0,
    "spendAllScrap": false,
    "cardsToDraw": 0,
    "cardsToDiscard": 0,
    "cardsToRetrieve": 0,
    "description": "Mystical tea that heals, buffs, restores mana, and retrieves 2 cards from discard!",
    "image": "assets/cards/MysticTea.png",
    "staticImage": "assets/cards/MysticTea.png",
    "animImage": null,
    "isAnimated": false
  },
  {
    "id": "s1-006",
    "series": 1,
    "number": 6,
    "code": "#1-006",
    "name": "Orange Juice",
    "class": "Elixir",
    "rarity": "Common",
    "cost": 1,
    "damage": 0,
    "damageType": "None",
    "isSplash": false,
    "armor": 0,
    "ward": 0,
    "healing": 5,
    "manaGain": 0,
    "buffAmount": 9,
    "buffDuration": 3,
    "debuffAmount": 0,
    "debuffDuration": 0,
    "burn": 0,
    "bleed": 0,
    "poison": 0,
    "stunChance": 0,
    "speedBonus": 3,
    "scrapGain": 0,
    "scrapCost": 0,
    "spendAllScrap": false,
    "cardsToDraw": 0,
    "cardsToDiscard": 0,
    "cardsToRetrieve": 0,
    "description": "Orange juice! Massive healing, buff, and speed boost!",
    "image": "assets/cards/OrangeJuice.png",
    "staticImage": "assets/cards/OrangeJuice.png",
    "animImage": null,
    "isAnimated": false
  },
  {
    "id": "s1-007",
    "series": 1,
    "number": 7,
    "code": "#1-007",
    "name": "Pear Juice",
    "class": "Elixir",
    "rarity": "Uncommon",
    "cost": 2,
    "damage": 4,
    "damageType": "Magic",
    "isSplash": false,
    "armor": 5,
    "ward": 3,
    "healing": 8,
    "manaGain": 2,
    "buffAmount": 0,
    "buffDuration": 0,
    "debuffAmount": 0,
    "debuffDuration": 0,
    "burn": 0,
    "bleed": 0,
    "poison": 0,
    "stunChance": 0,
    "speedBonus": 0,
    "scrapGain": 0,
    "scrapCost": 0,
    "spendAllScrap": false,
    "cardsToDraw": 0,
    "cardsToDiscard": 0,
    "cardsToRetrieve": 0,
    "description": "Refreshing pear juice that blasts foes with magic damage, heals, and grants defense, but inflicts bleed on you.",
    "image": "assets/cards/pearJuice.png",
    "staticImage": "assets/cards/pearJuice.png",
    "animImage": null,
    "isAnimated": false
  },
  {
    "id": "s1-029",
    "series": 1,
    "number": 29,
    "code": "#1-029",
    "name": "Pup",
    "class": "Animal",
    "rarity": "Common",
    "cost": 1,
    "damage": 3,
    "damageType": "Physical",
    "isSplash": false,
    "armor": 0,
    "ward": 0,
    "healing": 0,
    "manaGain": 0,
    "buffAmount": 0,
    "buffDuration": 0,
    "debuffAmount": 0,
    "debuffDuration": 0,
    "burn": 0,
    "bleed": 0,
    "poison": 0,
    "stunChance": 0,
    "speedBonus": 3,
    "scrapGain": 0,
    "scrapCost": 0,
    "spendAllScrap": false,
    "cardsToDraw": 1,
    "cardsToDiscard": 0,
    "cardsToRetrieve": 0,
    "description": "A quick little pup that gets you moving fast.",
    "image": "assets/cards/Pup.png",
    "staticImage": "assets/cards/Pup.png",
    "animImage": null,
    "isAnimated": false
  },
  {
    "id": "s1-020",
    "series": 1,
    "number": 20,
    "code": "#1-020",
    "name": "Pure Knight",
    "class": "Swordsman",
    "rarity": "Epic",
    "cost": 3,
    "damage": 10,
    "damageType": "Physical",
    "isSplash": false,
    "armor": 14,
    "ward": 7,
    "healing": 0,
    "manaGain": 0,
    "buffAmount": 0,
    "buffDuration": 0,
    "debuffAmount": 0,
    "debuffDuration": 0,
    "burn": 0,
    "bleed": 0,
    "poison": 0,
    "stunChance": 0,
    "speedBonus": 0,
    "scrapGain": 0,
    "scrapCost": 0,
    "spendAllScrap": false,
    "cardsToDraw": 0,
    "cardsToDiscard": 0,
    "cardsToRetrieve": 0,
    "description": "The best knight there could possibly be",
    "image": "assets/cards/PureKnight.png",
    "staticImage": "assets/cards/PureKnight.png",
    "animImage": null,
    "isAnimated": false
  },
  {
    "id": "s1-048",
    "series": 1,
    "number": 48,
    "code": "#1-048",
    "name": "Pureblade Lancer",
    "class": "Swordsman",
    "rarity": "Uncommon",
    "cost": 2,
    "damage": 9,
    "damageType": "Physical",
    "isSplash": false,
    "armor": 0,
    "ward": 0,
    "healing": 0,
    "manaGain": 0,
    "buffAmount": 0,
    "buffDuration": 0,
    "debuffAmount": 0,
    "debuffDuration": 0,
    "burn": 0,
    "bleed": 0,
    "poison": 0,
    "stunChance": 0,
    "speedBonus": 0,
    "scrapGain": 0,
    "scrapCost": 0,
    "spendAllScrap": false,
    "cardsToDraw": 0,
    "cardsToDiscard": 0,
    "cardsToRetrieve": 0,
    "description": "",
    "image": "assets/cards/Pureblade Lancer.png",
    "staticImage": "assets/cards/Pureblade Lancer.png",
    "animImage": null,
    "isAnimated": false
  },
  {
    "id": "s1-023",
    "series": 1,
    "number": 23,
    "code": "#1-023",
    "name": "Quill",
    "class": "Animal",
    "rarity": "Uncommon",
    "cost": 1,
    "damage": 4,
    "damageType": "Physical",
    "isSplash": false,
    "armor": 0,
    "ward": 0,
    "healing": 0,
    "manaGain": 0,
    "buffAmount": 3,
    "buffDuration": 2,
    "debuffAmount": 0,
    "debuffDuration": 0,
    "burn": 0,
    "bleed": 3,
    "poison": 0,
    "stunChance": 0,
    "speedBonus": 0,
    "scrapGain": 0,
    "scrapCost": 0,
    "spendAllScrap": false,
    "cardsToDraw": 0,
    "cardsToDiscard": 0,
    "cardsToRetrieve": 0,
    "description": "A sharp quill that attacks and increases your speed for 2 turns.",
    "image": "assets/cards/Quill.png",
    "staticImage": "assets/cards/Quill.png",
    "animImage": null,
    "isAnimated": false
  },
  {
    "id": "s1-028",
    "series": 1,
    "number": 28,
    "code": "#1-028",
    "name": "Rider",
    "class": "Animal",
    "rarity": "Uncommon",
    "cost": 2,
    "damage": 6,
    "damageType": "Physical",
    "isSplash": false,
    "armor": 5,
    "ward": 0,
    "healing": 0,
    "manaGain": 0,
    "buffAmount": 0,
    "buffDuration": 0,
    "debuffAmount": 0,
    "debuffDuration": 0,
    "burn": 0,
    "bleed": 0,
    "poison": 0,
    "stunChance": 0,
    "speedBonus": 3,
    "scrapGain": 0,
    "scrapCost": 0,
    "spendAllScrap": false,
    "cardsToDraw": 0,
    "cardsToDiscard": 0,
    "cardsToRetrieve": 0,
    "description": "A mounted fighter that strikes hard and keeps their guard up.",
    "image": "assets/cards/Rider.png",
    "staticImage": "assets/cards/Rider.png",
    "animImage": null,
    "isAnimated": false
  },
  {
    "id": "s1-034",
    "series": 1,
    "number": 34,
    "code": "#1-034",
    "name": "Rift",
    "class": "Wild Mages",
    "rarity": "Epic",
    "cost": 3,
    "damage": 14,
    "damageType": "Physical",
    "isSplash": false,
    "armor": 0,
    "ward": 0,
    "healing": 0,
    "manaGain": 0,
    "buffAmount": 0,
    "buffDuration": 0,
    "debuffAmount": 0,
    "debuffDuration": 0,
    "burn": 0,
    "bleed": 0,
    "poison": 0,
    "stunChance": 0,
    "speedBonus": -2,
    "scrapGain": 0,
    "scrapCost": 0,
    "spendAllScrap": false,
    "cardsToDraw": 0,
    "cardsToDiscard": 0,
    "cardsToRetrieve": 0,
    "description": "A warp in space that can strike hard and surge your speed.",
    "image": "assets/cards/Rift.png",
    "staticImage": "assets/cards/Rift.png",
    "animImage": null,
    "isAnimated": false
  },
  {
    "id": "s1-040",
    "series": 1,
    "number": 40,
    "code": "#1-040",
    "name": "Rift Devourer",
    "class": "Monster",
    "rarity": "Rare",
    "cost": 3,
    "damage": 10,
    "damageType": "Physical",
    "isSplash": true,
    "armor": 0,
    "ward": 0,
    "healing": 0,
    "manaGain": 0,
    "buffAmount": 0,
    "buffDuration": 0,
    "debuffAmount": 0,
    "debuffDuration": 0,
    "burn": 0,
    "bleed": 0,
    "poison": 0,
    "stunChance": 0,
    "speedBonus": 0,
    "scrapGain": 0,
    "scrapCost": 0,
    "spendAllScrap": false,
    "cardsToDraw": 1,
    "cardsToDiscard": 0,
    "cardsToRetrieve": 0,
    "description": "",
    "image": "assets/cards/Rift Devourer.png",
    "staticImage": "assets/cards/Rift Devourer.png",
    "animImage": null,
    "isAnimated": false
  },
  {
    "id": "s1-063",
    "series": 1,
    "number": 63,
    "code": "#1-063",
    "name": "Rustbomb Runner",
    "class": "Goblins",
    "rarity": "Rare",
    "cost": 3,
    "damage": 8,
    "damageType": "Magic",
    "isSplash": true,
    "armor": 0,
    "ward": 0,
    "healing": 0,
    "manaGain": 0,
    "buffAmount": 2,
    "buffDuration": 2,
    "debuffAmount": 0,
    "debuffDuration": 0,
    "burn": 2,
    "bleed": 0,
    "poison": 0,
    "stunChance": 0,
    "speedBonus": 0,
    "scrapGain": 0,
    "scrapCost": 0,
    "spendAllScrap": false,
    "cardsToDraw": 0,
    "cardsToDiscard": 0,
    "cardsToRetrieve": 0,
    "description": "A goblin runner who throws a rust bomb that burns a crowd.",
    "image": "assets/cards/anim/RustbombRunnerG.webp",
    "staticImage": "assets/cards/RustbombRunnerG.png",
    "animImage": "assets/cards/anim/RustbombRunnerG.webp",
    "isAnimated": true
  },
  {
    "id": "s1-068",
    "series": 1,
    "number": 68,
    "code": "#1-068",
    "name": "Scrap Mortar",
    "class": "Goblins",
    "rarity": "Rare",
    "cost": 5,
    "damage": 0,
    "damageType": "Magic",
    "isSplash": true,
    "armor": 0,
    "ward": 0,
    "healing": 0,
    "manaGain": 0,
    "buffAmount": 0,
    "buffDuration": 0,
    "debuffAmount": 0,
    "debuffDuration": 0,
    "burn": 0,
    "bleed": 0,
    "poison": 0,
    "stunChance": 0,
    "speedBonus": 0,
    "scrapGain": 0,
    "scrapCost": 1,
    "spendAllScrap": true,
    "cardsToDraw": 0,
    "cardsToDiscard": 0,
    "cardsToRetrieve": 0,
    "description": "Spend all Scrap to blast all enemies for 1 damage per Scrap. Upgraded: 2 damage per Scrap.",
    "image": "assets/cards/anim/ScrapMortarG.webp",
    "staticImage": "assets/cards/ScrapMortarG.png",
    "animImage": "assets/cards/anim/ScrapMortarG.webp",
    "isAnimated": true
  },
  {
    "id": "s1-061",
    "series": 1,
    "number": 61,
    "code": "#1-061",
    "name": "Scrap Slinger",
    "class": "Goblins",
    "rarity": "Uncommon",
    "cost": 2,
    "damage": 5,
    "damageType": "Physical",
    "isSplash": false,
    "armor": 0,
    "ward": 0,
    "healing": 0,
    "manaGain": 0,
    "buffAmount": 0,
    "buffDuration": 0,
    "debuffAmount": 0,
    "debuffDuration": 0,
    "burn": 0,
    "bleed": 0,
    "poison": 0,
    "stunChance": 0,
    "speedBonus": 0,
    "scrapGain": 0,
    "scrapCost": 0,
    "spendAllScrap": false,
    "cardsToDraw": 1,
    "cardsToDiscard": 0,
    "cardsToRetrieve": 0,
    "description": "A goblin who slings junk and keeps the hand moving.",
    "image": "assets/cards/anim/ScrapSlingerG.webp",
    "staticImage": "assets/cards/ScrapSlingerG.png",
    "animImage": "assets/cards/anim/ScrapSlingerG.webp",
    "isAnimated": true
  },
  {
    "id": "s1-070",
    "series": 1,
    "number": 70,
    "code": "#1-070",
    "name": "Shrapnel Sort",
    "class": "Goblins",
    "rarity": "Uncommon",
    "cost": 2,
    "damage": 4,
    "damageType": "Physical",
    "isSplash": false,
    "armor": 0,
    "ward": 0,
    "healing": 0,
    "manaGain": 0,
    "buffAmount": 0,
    "buffDuration": 0,
    "debuffAmount": 0,
    "debuffDuration": 0,
    "burn": 0,
    "bleed": 0,
    "poison": 0,
    "stunChance": 0,
    "speedBonus": 0,
    "scrapGain": 0,
    "scrapCost": 0,
    "spendAllScrap": false,
    "cardsToDraw": 0,
    "cardsToDiscard": 2,
    "cardsToRetrieve": 0,
    "description": "Discard 2 random cards to cut through the line and bleed the target for each one.",
    "image": "assets/cards/ShrapnelSortG.png",
    "staticImage": "assets/cards/ShrapnelSortG.png",
    "animImage": null,
    "isAnimated": false
  },
  {
    "id": "s1-014",
    "series": 1,
    "number": 14,
    "code": "#1-014",
    "name": "Skeleton",
    "class": "Monster",
    "rarity": "Common",
    "cost": 1,
    "damage": 4,
    "damageType": "Physical",
    "isSplash": false,
    "armor": 0,
    "ward": 0,
    "healing": 0,
    "manaGain": 0,
    "buffAmount": 0,
    "buffDuration": 0,
    "debuffAmount": 0,
    "debuffDuration": 0,
    "burn": 0,
    "bleed": 0,
    "poison": 0,
    "stunChance": 0,
    "speedBonus": 0,
    "scrapGain": 0,
    "scrapCost": 0,
    "spendAllScrap": false,
    "cardsToDraw": 0,
    "cardsToDiscard": 0,
    "cardsToRetrieve": 0,
    "description": "A skeletal warrior rises to fight. Deals 8 damage.",
    "image": "assets/cards/Skeleton.png",
    "staticImage": "assets/cards/Skeleton.png",
    "animImage": null,
    "isAnimated": false
  },
  {
    "id": "s1-012",
    "series": 1,
    "number": 12,
    "code": "#1-012",
    "name": "Slot Machine",
    "class": "Monster",
    "rarity": "Epic",
    "cost": 3,
    "damage": 0,
    "damageType": "Magic",
    "isSplash": false,
    "armor": 0,
    "ward": 0,
    "healing": 0,
    "manaGain": 0,
    "buffAmount": 0,
    "buffDuration": 0,
    "debuffAmount": 0,
    "debuffDuration": 0,
    "burn": 0,
    "bleed": 0,
    "poison": 0,
    "stunChance": 0,
    "speedBonus": 0,
    "scrapGain": 0,
    "scrapCost": 0,
    "spendAllScrap": false,
    "cardsToDraw": 2,
    "cardsToDiscard": 0,
    "cardsToRetrieve": 0,
    "description": "Draw 3 random cards.",
    "image": "assets/cards/SlotMachine.png",
    "staticImage": "assets/cards/SlotMachine.png",
    "animImage": null,
    "isAnimated": false
  },
  {
    "id": "s1-018",
    "series": 1,
    "number": 18,
    "code": "#1-018",
    "name": "Sun Splitter",
    "class": "Swordsman",
    "rarity": "Uncommon",
    "cost": 2,
    "damage": 6,
    "damageType": "None",
    "isSplash": true,
    "armor": 0,
    "ward": 0,
    "healing": 0,
    "manaGain": 0,
    "buffAmount": 0,
    "buffDuration": 0,
    "debuffAmount": 0,
    "debuffDuration": 0,
    "burn": 3,
    "bleed": 0,
    "poison": 0,
    "stunChance": 0,
    "speedBonus": 0,
    "scrapGain": 0,
    "scrapCost": 0,
    "spendAllScrap": false,
    "cardsToDraw": 0,
    "cardsToDiscard": 0,
    "cardsToRetrieve": 0,
    "description": "Apply 4 burn to every enemy.",
    "image": "assets/cards/SunSplitter.png",
    "staticImage": "assets/cards/SunSplitter.png",
    "animImage": null,
    "isAnimated": false
  },
  {
    "id": "s1-016",
    "series": 1,
    "number": 16,
    "code": "#1-016",
    "name": "Targeted Smite",
    "class": "Swordsman",
    "rarity": "Exotic",
    "cost": 10,
    "damage": 200,
    "damageType": "None",
    "isSplash": false,
    "armor": 0,
    "ward": 0,
    "healing": 0,
    "manaGain": 0,
    "buffAmount": 0,
    "buffDuration": 0,
    "debuffAmount": 0,
    "debuffDuration": 0,
    "burn": 0,
    "bleed": 0,
    "poison": 0,
    "stunChance": 0,
    "speedBonus": 0,
    "scrapGain": 0,
    "scrapCost": 0,
    "spendAllScrap": false,
    "cardsToDraw": 0,
    "cardsToDiscard": 0,
    "cardsToRetrieve": 0,
    "description": "Deal 24 damage to one target enemy.",
    "image": "assets/cards/anim/TargetedSmite.webp",
    "staticImage": "assets/cards/TargetedSmite.png",
    "animImage": "assets/cards/anim/TargetedSmite.webp",
    "isAnimated": true
  },
  {
    "id": "s1-058",
    "series": 1,
    "number": 58,
    "code": "#1-058",
    "name": "Tinpicker Scout",
    "class": "Goblins",
    "rarity": "Common",
    "cost": 1,
    "damage": 0,
    "damageType": "Physical",
    "isSplash": false,
    "armor": 0,
    "ward": 0,
    "healing": 0,
    "manaGain": 0,
    "buffAmount": 0,
    "buffDuration": 0,
    "debuffAmount": 0,
    "debuffDuration": 0,
    "burn": 0,
    "bleed": 0,
    "poison": 0,
    "stunChance": 0,
    "speedBonus": 0,
    "scrapGain": 0,
    "scrapCost": 0,
    "spendAllScrap": false,
    "cardsToDraw": 1,
    "cardsToDiscard": 0,
    "cardsToRetrieve": 0,
    "description": "A nimble goblin scout who rummages fast and draws support.",
    "image": "assets/cards/anim/TinpickerScout.webp",
    "staticImage": "assets/cards/TinpickerScout.png",
    "animImage": "assets/cards/anim/TinpickerScout.webp",
    "isAnimated": true
  },
  {
    "id": "s1-022",
    "series": 1,
    "number": 22,
    "code": "#1-022",
    "name": "Tortoise",
    "class": "Animal",
    "rarity": "Rare",
    "cost": 2,
    "damage": 3,
    "damageType": "Physical",
    "isSplash": false,
    "armor": 10,
    "ward": 6,
    "healing": 0,
    "manaGain": 0,
    "buffAmount": 0,
    "buffDuration": 0,
    "debuffAmount": 0,
    "debuffDuration": 0,
    "burn": 0,
    "bleed": 0,
    "poison": 0,
    "stunChance": 0,
    "speedBonus": -3,
    "scrapGain": 0,
    "scrapCost": 0,
    "spendAllScrap": false,
    "cardsToDraw": 0,
    "cardsToDiscard": 0,
    "cardsToRetrieve": 0,
    "description": "A resilient tortoise that guards you with heavy armor but moves slowly.",
    "image": "assets/cards/Tortoise.png",
    "staticImage": "assets/cards/Tortoise.png",
    "animImage": null,
    "isAnimated": false
  },
  {
    "id": "s1-056",
    "series": 1,
    "number": 56,
    "code": "#1-056",
    "name": "Void Dice Savant",
    "class": "Wild Mages",
    "rarity": "Epic",
    "cost": 6,
    "damage": 0,
    "damageType": "Magic",
    "isSplash": false,
    "armor": 0,
    "ward": 0,
    "healing": 0,
    "manaGain": 0,
    "buffAmount": 0,
    "buffDuration": 0,
    "debuffAmount": 0,
    "debuffDuration": 0,
    "burn": 0,
    "bleed": 0,
    "poison": 0,
    "stunChance": 0,
    "speedBonus": 0,
    "scrapGain": 0,
    "scrapCost": 0,
    "spendAllScrap": false,
    "cardsToDraw": 1,
    "cardsToDiscard": 0,
    "cardsToRetrieve": 0,
    "description": "",
    "image": "assets/cards/Dice.png",
    "staticImage": "assets/cards/Dice.png",
    "animImage": null,
    "isAnimated": false
  },
  {
    "id": "s1-037",
    "series": 1,
    "number": 37,
    "code": "#1-037",
    "name": "Wine",
    "class": "Elixir",
    "rarity": "Rare",
    "cost": 2,
    "damage": 0,
    "damageType": "Physical",
    "isSplash": false,
    "armor": 0,
    "ward": 0,
    "healing": 16,
    "manaGain": 0,
    "buffAmount": 0,
    "buffDuration": 0,
    "debuffAmount": 0,
    "debuffDuration": 0,
    "burn": 0,
    "bleed": 0,
    "poison": 0,
    "stunChance": 0,
    "speedBonus": -2,
    "scrapGain": 0,
    "scrapCost": 0,
    "spendAllScrap": false,
    "cardsToDraw": 0,
    "cardsToDiscard": 0,
    "cardsToRetrieve": 0,
    "description": "A dangerous brew that heals you at a price of slowed reflexes.",
    "image": "assets/cards/Wine.png",
    "staticImage": "assets/cards/Wine.png",
    "animImage": null,
    "isAnimated": false
  }
];

const GAME_HEROES = [
  {
    "name": "Deck Monk",
    "title": "The Master of Balance",
    "hp": 100,
    "damage": 10,
    "mana": 15,
    "unlock": "Default Unlocked (Available at Start)",
    "passive": "Standard balanced starting deck. No penalties, rock-solid consistency across all classes.",
    "affinity": "Swordsman & Elixir",
    "description": "The starter hero. A balanced monk with standard stats and no special abilities. Perfect for learning the game.",
    "sprite": "assets/heroes/DeckMonk.png"
  },
  {
    "name": "Demonling",
    "title": "The Brimstone Imp",
    "hp": 90,
    "damage": 11,
    "mana": 15,
    "unlock": "Own Lil' Demon & Daddy Demon + Play them + 20 Burn kills",
    "passive": "Hero basic attacks inflict persistent Burn. Turn start summons Lil' Demon-litionist (75% chance) or Daddy Demon-litionist (25% chance) directly into hand!",
    "affinity": "Monster & Pyromancy",
    "description": "An infernal demonling who scorches foes and calls on demon allies each turn. His attacks apply burn from this resource, and at the start of each turn he summons Lil Demon Litionist 75% of the time or Daddy Demon Litionist 25% of the time.",
    "sprite": "assets/heroes/Demonling.png"
  },
  {
    "name": "Gorilla Gabe",
    "title": "The Primal Behemoth",
    "hp": 150,
    "damage": 12,
    "mana": 10,
    "unlock": "Default Unlocked (Available at Start)",
    "passive": "Colossal 150 HP pool and 12 Base Attack. Suffers from a constrained 10 Max Mana pool.",
    "affinity": "Swordsman & Brute Force",
    "description": "A mighty gorilla with tremendous health and solid damage, but limited mana reserves. Survives through raw power and endurance.",
    "sprite": "assets/heroes/GorillaGabe.png"
  },
  {
    "name": "Hunter The Hedgehog",
    "title": "The Spiny Vanguard",
    "hp": 140,
    "damage": 10,
    "mana": 8,
    "unlock": "Own Quill & Hedgehog + Play them + 15 Bleed/Wound kills + 5 Elite wins + Shop purchase",
    "passive": "Hero basic attack strikes ALL living foes simultaneously and inflicts stackable Bleed! Summons Quill (80%) or Hedgehog (20%) each turn.",
    "affinity": "Animal & Bleed Tactics",
    "description": "Hunter rains damage on all enemies and wounds them with each hero attack. At start of turn, he summons Quill 80% of the time and Hedgehog 20% of the time.",
    "sprite": "assets/heroes/Hunter the Hedgehog.png"
  },
  {
    "name": "Lost Spirit",
    "title": "The Ethereal Reclaimer",
    "hp": 80,
    "damage": 15,
    "mana": 14,
    "unlock": "Play Grim Reaper 15 times",
    "passive": "+1 Card Draw every turn! Can retrieve up to 4 cards from discard pile back to hand or deck.",
    "affinity": "Wild Mages & Discard Cycling",
    "description": "A powerful spirit with high damage output. Draws an extra card each turn and can recycle 5 cards from the discard pile after each fight.",
    "sprite": "assets/heroes/lostspirit.png"
  },
  {
    "name": "Necri",
    "title": "Mistress of the Bone Crypt",
    "hp": 70,
    "damage": 12,
    "mana": 20,
    "unlock": "Own Skeleton card + 15 Elite victories + 20 Normal victories",
    "passive": "Starts with 8 Bone Ward; regenerates +2 HP per turn; automatically summons a Skeleton into hand every single turn!",
    "affinity": "Monster & Graveyard Swarm",
    "description": "A powerful necromancer who channels the dark arts. Starts each combat with bone ward and regenerates 2 health per turn. Summons a skeleton warrior each turn to fight alongside you.",
    "sprite": "assets/heroes/Necri.png"
  },
  {
    "name": "Scrap Goblin",
    "title": "The Junk Engine Tinkerer",
    "hp": 90,
    "damage": 9,
    "mana": 13,
    "unlock": "Play 20 Goblins cards + 10 Elite victories",
    "passive": "Converts discards to Scrap (+1 passive per discard, +2 active hero scavenge ability). Unlocks 4 in-combat contraption abilities (Draw, Damage, Speed, Reclaim) upgradeable up to Level 3!",
    "affinity": "Goblins & Scrap Recycler",
    "description": "Scrap Goblin \u2014 A scavenging hero who converts discarded cards into Scrap.\n\nPassive: Any card discarded grants 1 Scrap.\nHero Scavenge Ability (Once per turn): Discard cards to gain 2 Scrap per card.\nSpend Scrap Contraptions: Draw, Damage, Speed, and Reclaim abilities upgradeable up to Level 3.\nReclaim returns cards from discard to deck or hand.",
    "sprite": "assets/enemies/Goblin.png"
  }
];

const GAME_RELICS = [
  {
    "name": "Golden Pouch",
    "cost": 3,
    "costType": "Relic Shards",
    "effect": "+10% Gold Gain",
    "tactical": "Multiplies gold income from combats and campsites, funding heavy shop shopping sprees.",
    "description": "+10% gold gain from combat and treasure rewards"
  },
  {
    "name": "Hexglass Lens",
    "cost": 3,
    "costType": "Relic Shards",
    "effect": "-4 Enemy Starting Ward",
    "tactical": "All foes begin battle with 4 less Ward, enabling Wild Mages spells to pierce defenses instantly.",
    "description": "Enemies start combat with -4 ward"
  },
  {
    "name": "Iron Heart",
    "cost": 3,
    "costType": "Relic Shards",
    "effect": "+10 Max HP",
    "tactical": "Boosts baseline survivability at run start. Crucial for glass-cannon heroes like Necri and Lost Spirit.",
    "description": "+10 max HP at run start"
  },
  {
    "name": "Keen Edge",
    "cost": 3,
    "costType": "Relic Shards",
    "effect": "+2 Base ATK",
    "tactical": "Permanent damage bonus applied to every basic hero attack. Synergizes with Hunter hitting all targets.",
    "description": "+2 base attack at run start"
  },
  {
    "name": "Mana Lens",
    "cost": 3,
    "costType": "Relic Shards",
    "effect": "+1 Max Mana",
    "tactical": "Expands turn mana limit from 15 to 16. Empowers high-cost spells and expensive summons.",
    "description": "+1 max mana at run start"
  },
  {
    "name": "Quick Study",
    "cost": 3,
    "costType": "Relic Shards",
    "effect": "+1 Opening Draw",
    "tactical": "Draw 1 extra card on Turn 1 of every combat to immediately assemble lethal combos.",
    "description": "+1 opening card draw"
  },
  {
    "name": "Ruinous Seal",
    "cost": 3,
    "costType": "Relic Shards",
    "effect": "-15% Enemy Starting HP",
    "tactical": "Reduces starting enemy HP by 15%. Devastating against high-health Elites and Act Bosses.",
    "description": "Enemies start combat with -8% health"
  },
  {
    "name": "Sundered Chisel",
    "cost": 3,
    "costType": "Relic Shards",
    "effect": "-3 Enemy Starting Armor",
    "tactical": "Shatters 3 Armor from all enemies at battle start, allowing Swordsman strikes to deal pure damage.",
    "description": "Enemies start combat with -3 armor"
  },
  {
    "name": "Withering Banner",
    "cost": 3,
    "costType": "Relic Shards",
    "effect": "-7% Enemy Attack",
    "tactical": "Permanently blunts all incoming enemy strike power across every dungeon floor.",
    "description": "Enemies start combat with -7% attack"
  }
];

const GAME_PACKS = [
  {
    "id": "common",
    "name": "Common Pack",
    "cost": 150,
    "currency": "Gems",
    "cardCount": 6,
    "badge": "Entry Draft",
    "description": "Standard booster pack. Ideal for expanding initial card collection and discovering staple mechanics.",
    "rates": {
      "Common": 67.5,
      "Uncommon": 22.0,
      "Rare": 7.0,
      "Epic": 2.2,
      "Legendary": 0.8,
      "Exotic": 0.5
    },
    "guarantee": null
  },
  {
    "id": "rare",
    "name": "Rare Pack",
    "cost": 350,
    "currency": "Gems",
    "cardCount": 6,
    "badge": "High Tier",
    "description": "Packed with concentrated rare magic. 48% chance of Rare per card slot with elevated Epic/Legendary rates.",
    "rates": {
      "Common": 10.0,
      "Uncommon": 22.0,
      "Rare": 48.0,
      "Epic": 14.0,
      "Legendary": 5.0,
      "Exotic": 1.0
    },
    "guarantee": "High Rare Concentration"
  },
  {
    "id": "exotic",
    "name": "Exotic Pack",
    "cost": 1050,
    "currency": "Gems",
    "cardCount": 8,
    "badge": "Guaranteed Foil",
    "description": "The crown jewel of gacha packs! Contains 1 Guaranteed Exotic + 1 Guaranteed Legendary + 6 high-tier cards.",
    "rates": {
      "Uncommon": 2.0,
      "Rare": 10.0,
      "Epic": 34.0,
      "Legendary": 32.0,
      "Exotic": 22.0
    },
    "guarantee": "1 Guaranteed Exotic + 1 Guaranteed Legendary"
  },
  {
    "id": "bundle",
    "name": "Collector's Bundle Box",
    "cost": 1600,
    "currency": "Gems",
    "cardCount": 38,
    "badge": "Maximum Value",
    "description": "Massive 38-card box bundle combining 3 Common Packs + 2 Rare Packs + 1 Exotic Pack with substantial Gem savings!",
    "rates": {
      "Common": 40.0,
      "Uncommon": 25.0,
      "Rare": 20.0,
      "Epic": 8.0,
      "Legendary": 5.0,
      "Exotic": 2.0
    },
    "guarantee": "Includes 1 Guaranteed Exotic & 1 Guaranteed Legendary"
  }
];

const GAME_ACTS = [
  {
    act: 1,
    name: "The Descent",
    floors: 12,
    theme: "Dungeon Catacombs & Crypts",
    bossPool: [
      {
        name: "Bone Amalgam",
        hp: 220,
        atk: 14,
        armor: 12,
        ward: 0,
        desc: "Undead Behemoth fused from thousands of skeletal remains. Has high physical armor and counter bone spikes.",
        sprite: "assets/enemies/EliteKnight.png"
      },
      {
        name: "Archmage Ignis",
        hp: 175,
        atk: 16,
        armor: 0,
        ward: 15,
        desc: "Corrupted pyromancer trapped in the dungeon vault. Inflicts heavy Burn stacks and reflects damage with Flame Shield.",
        sprite: "assets/enemies/Cultist.png"
      },
      {
        name: "Wreckyard Colossus",
        hp: 260,
        atk: 18,
        armor: 15,
        ward: 5,
        desc: "Rusted iron titan resurrected by Goblin junk-sorcery. Steam Vent deals recoil damage when cards are discarded.",
        sprite: "assets/enemies/Goblin.png"
      }
    ]
  },
  {
    act: 2,
    name: "The Core & Trials",
    floors: 10,
    theme: "Molten Core & Ancient Forge",
    bossPool: [
      {
        name: "Magma Behemoth",
        hp: 380,
        atk: 22,
        armor: 20,
        ward: 18,
        desc: "Forged in the heart of the core, melts player defenses and summons flaming minions.",
        sprite: "assets/enemies/Bandit.png"
      }
    ]
  },
  {
    act: 3,
    name: "The Primordial Summit",
    floors: 18,
    theme: "Astral Peak & Sky Realm",
    bossPool: [
      {
        name: "Ascended Sovereign",
        hp: 650,
        atk: 28,
        armor: 30,
        ward: 25,
        desc: "Act 3 Final Boss. Supreme ruler of the celestial summit commanding astral magic and radiant defenses.",
        sprite: "assets/cards/Ashmaw Colossus.png"
      }
    ]
  }
];

const MYSTERY_EVENTS = [
  {
    id: 1,
    name: "The Cursed Altar",
    icon: "🕯️",
    lore: "An ancient crimson altar hums with dark sacrificial power. It demands blood in exchange for martial prowess.",
    choices: [
      { label: "Accept Blood Pact", outcome: "+4 Base Attack, -15 Max HP", effect: { atk: 4, maxHp: -15 } },
      { label: "Purify Altar", outcome: "Pay 30 Gold -> Gain 45 Gems, Heal 20 HP", effect: { gold: -30, gems: 45, hp: 20 } },
      { label: "Leave It Untouched", outcome: "Safely walk away with no changes", effect: {} }
    ]
  },
  {
    id: 2,
    name: "The Wandering Alchemist",
    icon: "🧪",
    lore: "A cloaked apothecary sits beside bubbling flasks offering experimental draughts.",
    choices: [
      { label: "Chug Glowing Flask", outcome: "50% chance +20 Max HP & Full Heal; 50% chance 15 damage", effect: { gamble: "flask" } },
      { label: "Buy Relic Distillate", outcome: "Pay 35 Gold -> Gain 2 Relic Shards", effect: { gold: -35, relicShards: 2 } },
      { label: "Politely Decline", outcome: "Decline and move forward", effect: {} }
    ]
  },
  {
    id: 3,
    name: "The Slumbering Golem's Cache",
    icon: "🗿",
    lore: "A dormant runic golem lies slumped over a glittering cache of ancient gold and gemstone shards.",
    choices: [
      { label: "Carefully Pocket Gold", outcome: "Gain +75 Gold safely without disturbing the guardian", effect: { gold: 75 } },
      { label: "Pry Core Relic!", outcome: "Disturb the golem! Take 20 kinetic damage -> Gain 3 Relic Shards & 100 Gold", effect: { hp: -20, relicShards: 3, gold: 100 } },
      { label: "Tiptoe Past Silently", outcome: "Rest quietly (+15 HP)", effect: { hp: 15 } }
    ]
  },
  {
    id: 4,
    name: "The Arcane Anvil",
    icon: "⚒️",
    lore: "Ghostly blue flames burn inside a celestial forge. An ancient hammer rests on the anvil.",
    choices: [
      { label: "Temper Spirit", outcome: "Gain +10 Max HP & Full Health Recovery", effect: { maxHp: 10, fullHeal: true } },
      { label: "Transmute Wealth", outcome: "Pay 35 Gold -> Receive 50 Gems", effect: { gold: -35, gems: 50 } },
      { label: "Step Back", outcome: "Observe respectfully and move on", effect: {} }
    ]
  },
  {
    id: 5,
    name: "The Whispering Deck",
    icon: "🃏",
    lore: "A spectral card table materializes from the gloom. Ethereal cards orbit a glowing obsidian pedestal.",
    choices: [
      { label: "Infuse with Void Energy", outcome: "Sacrifice 20 HP -> Gain +5 Base Attack and 35 Gems", effect: { hp: -20, atk: 5, gems: 35 } },
      { label: "Study Ethereal Runes", outcome: "Gain 45 Gold and 1 Relic Shard", effect: { gold: 45, relicShards: 1 } },
      { label: "Walk Away Unscathed", outcome: "Leave safely", effect: {} }
    ]
  },
  {
    id: 6,
    name: "The Fountain of Cleansing",
    icon: "⛲",
    lore: "A crystalline basin spills with glowing azure spring water, radiating healing celestial mist.",
    choices: [
      { label: "Drink Deeply", outcome: "Restore 35 Health points", effect: { hp: 35 } },
      { label: "Toss Offering", outcome: "Pay 25 Gold -> Gain +15 Max HP & Full Heal", effect: { gold: -25, maxHp: 15, fullHeal: true } },
      { label: "Bottle Spring Essence", outcome: "Collect 2 Relic Shards", effect: { relicShards: 2 } }
    ]
  },
  {
    id: 7,
    name: "The Wandering Trickster",
    icon: "🎲",
    lore: "A goblin jester in a velvet coat tosses prismatic dice with uncanny dexterity.",
    choices: [
      { label: "High-Stakes Coin Flip", outcome: "50% chance +150 Gold; 50% chance lose 30 Gold or take 12 damage", effect: { gamble: "coin" } },
      { label: "Buy Loaded Die", outcome: "Pay 40 Gold -> Gain 2 Relic Shards and 25 Gems", effect: { gold: -40, relicShards: 2, gems: 25 } },
      { label: "Refuse to Play", outcome: "Walk away safely", effect: {} }
    ]
  },
  {
    id: 8,
    name: "Tomb of the Forgotten Knight",
    icon: "⚔️",
    lore: "A heavy stone sarcophagus bears the runic broadsword and sigil of an ancient crusader.",
    choices: [
      { label: "Pry the Blessed Blade", outcome: "Suffer 15 hex damage -> Gain +6 Base Attack", effect: { hp: -15, atk: 6 } },
      { label: "Leave Respectful Offering", outcome: "Pay 20 Gold -> Receive +10 Max HP and 30 Gems", effect: { gold: -20, maxHp: 10, gems: 30 } },
      { label: "Loot Crypt Chest", outcome: "Crack open auxiliary chest for 60 Gold", effect: { gold: 60 } }
    ]
  },
  {
    id: 9,
    name: "The Mirror of Souls",
    icon: "🪞",
    lore: "An ornate obsidian mirror reflects an astral apparition burning with celestial nebulae.",
    choices: [
      { label: "Gaze into Astral Abyss", outcome: "Sacrifice 10 Max HP -> Receive 4 Relic Shards", effect: { maxHp: -10, relicShards: 4 } },
      { label: "Shatter the Glass Entity", outcome: "Suffer 14 damage -> Gain 85 Gold and 30 Gems", effect: { hp: -14, gold: 85, gems: 30 } },
      { label: "Avert Your Eyes", outcome: "Walk away safely", effect: {} }
    ]
  },
  {
    id: 10,
    name: "The Goblin Black Market",
    icon: "🎪",
    lore: "A reinforced iron wagon sits guarded by lantern sentries, laden with contraband antiquities.",
    choices: [
      { label: "Buy Military Iron Rations", outcome: "Pay 25 Gold -> Heal 30 HP & +5 Max HP", effect: { gold: -25, hp: 30, maxHp: 5 } },
      { label: "Smuggle Contraband Relic", outcome: "Pay 50 Gold -> Gain 3 Relic Shards", effect: { gold: -50, relicShards: 3 } },
      { label: "Pawn Battlefield Scrap", outcome: "Gain +25 Gold", effect: { gold: 25 } }
    ]
  },
  {
    id: 11,
    name: "The Starlight Nexus",
    icon: "🌌",
    lore: "Dungeon stone gives way to an astral pocket dimension where nebula dust drifts peacefully.",
    choices: [
      { label: "Cosmic Meditation", outcome: "Restore 25 HP and gather 50 Gems", effect: { hp: 25, gems: 50 } },
      { label: "Harvest Astral Stardust", outcome: "Suffer 12 astral damage -> Gain 3 Relic Shards and 60 Gold", effect: { hp: -12, relicShards: 3, gold: 60 } },
      { label: "Absorb Ambient Quietude", outcome: "Catch your breath (+15 HP)", effect: { hp: 15 } }
    ]
  },
  {
    id: 12,
    name: "The Bloodbound Merchant",
    icon: "🩸",
    lore: "A pale aristocrat in crimson silks offers ancient reliquaries in exchange for vital essence.",
    choices: [
      { label: "Sacrifice Blood for Power", outcome: "Suffer 20 damage -> Gain +5 Base Attack and 40 Gold", effect: { hp: -20, atk: 5, gold: 40 } },
      { label: "Trade Life for Relic Shards", outcome: "Suffer 25 damage -> Gain 3 Relic Shards and 35 Gems", effect: { hp: -25, relicShards: 3, gems: 35 } },
      { label: "Politely Decline", outcome: "Refuse and move on", effect: {} }
    ]
  }
];

if (typeof window !== 'undefined') {
  window.GAME_CARDS = GAME_CARDS;
  window.GAME_HEROES = GAME_HEROES;
  window.GAME_RELICS = GAME_RELICS;
  window.GAME_PACKS = GAME_PACKS;
  window.GAME_ACTS = GAME_ACTS;
  window.MYSTERY_EVENTS = MYSTERY_EVENTS;
}
